<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="D-1011" name="com.test.admin.uiAutomation.homePage.TC003_verifyLoginWithDifferentRecords" tests="3" failures="1" timestamp="28 Sep 2018 19:25:36 GMT" time="19.401" errors="0">
  <testcase name="testLogin" time="8.054" classname="com.test.admin.uiAutomation.homePage.TC003_verifyLoginWithDifferentRecords">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.test.admin.uiAutomation.homePage.TC003_verifyLoginWithDifferentRecords.testLogin(TC003_verifyLoginWithDifferentRecords.java:59)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </failure>
  </testcase> <!-- testLogin -->
  <testcase name="testLogin" time="5.569" classname="com.test.admin.uiAutomation.homePage.TC003_verifyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- testLogin -->
  <testcase name="testLogin" time="5.778" classname="com.test.admin.uiAutomation.homePage.TC003_verifyLoginWithDifferentRecords">
    <skipped/>
  </testcase> <!-- testLogin -->
</testsuite> <!-- com.test.admin.uiAutomation.homePage.TC003_verifyLoginWithDifferentRecords -->
